---
- name: Docker run
  hosts: all
  become: true
  tasks:

    - name: Pull image
      docker_image:
        name: statusxt/otus-reddit
        tag: 1.0
        state: present

    - name: Run container
      docker_container:
        name: reddit
        image: statusxt/otus-reddit:1.0
        detach: yes
        network_mode: host
        ports:
          - "9292:9292"
        state: started
