FROM alpine:3.7
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
COPY . $APP_HOME/

RUN apk --update add --no-cache \
    ruby \
    ruby-dev \
    ruby-bundler \
    ruby-json \
    build-base \
    && bundle install \
    && rm -rf /var/cache/apk

ENV POST_SERVICE_HOST post \
    POST_SERVICE_PORT 5000 \
    COMMENT_SERVICE_HOST comment \
    COMMENT_SERVICE_PORT 9292

CMD ["puma"]
